# create build for local docker file

services:
  information_retrieval:
    build: .
    # restart: always
    # mount the folders image and output
    # labels:
    #   traefik.enable: true
    #   traefik.http.services.chat-svc.loadbalancer.server.port: 8001
    #   traefik.http.routers.chat-rtr.rule: Host("chat.ai-adesso.de")
    #   traefik.http.routers.chat-rtr.service: chat-svc
    #   traefik.http.routers.chat-rtr.entrypoints: https


    volumes:
      - ./data/input:/data/input
      - ./data/output:/data/output
      - ./logs:/logs

    # expose the port 8001
    ports:
      - "8001:8001"
    # # expose the port 8001
    # networks:
    #   - web

# networks:
#   web:
#     name: traefik_web
#     external: true
